### PR TITLE
fix: Update RuleVisitor type

### LINKED ISSUE #134: Change Request: Update RuleVisitor interface
### Which packages would you like to change?

- [ ] `@eslint/compat`
- [ ] `@eslint/config-array`
- [x] `@eslint/core`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`
- [ ] `@eslint/plugin-kit`

### What problem do you want to solve?

The `RuleVisitor` interface is currently defined as follows:

```ts
export interface RuleVisitor {
	/**
	 * Called for each node in the AST or at specific times during the traversal.
	 */
	[key: string]: (...args: any[]) => void;
}
```

However, this is causing problems when trying to extend `RuleVisitor` under `strict` TypeScript mode, as seen in these PRs:

* https://github.com/eslint/json/pull/66
* https://github.com/eslint/eslint/pull/19157

The errors take the form of the following:

```
error TS2411: Property 'Document' of type '((node: DocumentNode$1) => void) | undefined' is not assignable to 'string' index type '(...args: any[]) => void'.
```

### What do you think is the correct solution?

The problem is that the method defined in `RuleVisitor` is not optional. 

I can see a few different options:

1. **Remove all methods.** We can remove any predefined methods from `RuleVisitor` and leave essentially a blank interface:

```diff
export interface RuleVisitor {
	/**
	 * Called for each node in the AST or at specific times during the traversal.
	 */
-	[key: string]: (...args: any[]) => void;
}
```

That would give consumers something to extend from so that it logically looks like there's some relationship between the core types and consumer types. I'm not sure it's valuable.

2. **Convert to a mapped type.** We can change it to a mapped type as suggested by @fasttime [here](https://github.com/eslint/json/pull/66#issuecomment-2494418079):

```diff
- export interface RuleVisitor {
+ export type RuleVisitor = {
	/**
	 * Called for each node in the AST or at specific times during the traversal.
	 */
-	[key: string]: (...args: any[]) => void;
+	[key in string]?: (...args: any[]) => void;
}
```

Defining all methods to be optional also seems to make `RuleVisitor` mostly useless. 

3. **Eliminate `RuleVisitor` interface completely.** Because we don't know what the visitor will look like for any particular language, maybe it's a bad idea to try and enforce anything in particular. We could just define the `RuleDefinitionTypeOptions#Visitor` as `Object`, which would allow any non-primitive type to be used, and then we don't need `RuleVisitor` at all:

```diff
export interface RuleDefinitionTypeOptions {
	LangOptions: LanguageOptions;
	Code: SourceCode;
	RuleOptions: unknown[];
-	Visitor: RuleVisitor;
+	Visitor: Object;
	Node: unknown;
	MessageIds: string;
	ExtRuleDocs: unknown;
}
```

I think this is my favorite approach, but I'd like some insights from @JoshuaKGoldberg and @fasttime on all of the options and their ramifications.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by nzakas**
#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Make `RuleVisitor` type work practically with subinterfaces.

#### What changes did you make? (Give an overview)

- Converted `RuleVisitor` interface into a mapped type.

#### Related Issues

fixes #134

#### Is there anything you'd like reviewers to focus on?

The typescript-eslint rule recommended using a record instead of an object type. Does that make sense?

### CODE REVIEW

File: packages/core/src/types.ts [hunk 1]
```diff
@@ -92,20 +92,14 @@ export type RuleType = "problem" | "suggestion" | "layout";
...
  * times during the traversal.
  */
-export interface RuleVisitor {
-	/**
-	 * Called for each node in the AST or at specific times during the traversal.
-	 */
-	[key: string]: (...args: any[]) => void;
-}
-/* eslint-enable @typescript-eslint/consistent-indexed-object-style -- Needs to be interface so people can extend it. */
+export type RuleVisitor = Record<string, (...args: any[]) => void>;
```
Comment (fasttime) [inline packages/core/src/types.ts:101]: The value type should include `undefined` so that it's possible to define optional properties when TS option `strictNullChecks` is set:

```suggestion
export type RuleVisitor = Record<string, ((...args: any[]) => void) | undefined>;
```

**Comment by fasttime** [comment]
Oh, now Prettier 3.4 is complaining because of the formatting of Markdown files. It's the same problem as with eslint/json#67.

image

**Comment by nzakas** [comment]
I guess their semver policy isn't a strict as ours. :smile:

**Review by fasttime — APPROVED** [review]
LGTM, thanks!
